export const SCREEN_X = 1920
export const SCREEN_Y = 1080
export const PLANE_WIDTH = 440
export const PLANE_LENGTH = 2000
export const SIDE_BAR_WIDTH = 400
export const BLOCK_RANGE_LOW = -560
export const BLOCK_LENGTHX = 104
export const BLOCK_LENGTHY = 5
export const BLOCK_LENGTHZ = 12
export const ROW_WIDTH = 110
export const BLOCK_OFFSET = (ROW_WIDTH - BLOCK_LENGTHX) / 2
export const HERO_LENGTH = 14
export const HERO_BASELINE = -464
export const HERO_MOVINGSPEED = 8
export const HERO_JUMPINGSPEED = 9
export const DIR_NONE = 0
export const DIR_LEFT = 1
export const DIR_RIGHT = 2
export const DIR_UP = 3
export const GRAVITY = 0.4
export const HERO_TOTAL_FX = Math.round(ROW_WIDTH / HERO_MOVINGSPEED)
export const HERO_TOTAL_FZ = Math.round(2 * HERO_JUMPINGSPEED / GRAVITY)
export const HERO_ENERGY_LIMIT = 100
export const HERO_ENERGY_REWARD = 50
export const HERO_OFFSET = (ROW_WIDTH - HERO_LENGTH) / 2
export const HERO_RADIUS = HERO_LENGTH / 2
export const GAME_START_FRAME = 90
export const INITIAL_SCENE_OFFSETX = 500
export const SWITCH_SHORT_FRAME = 45
export const READY_BUTTON_LX = 480
export const READY_BUTTON_LY = 80
export const PHOTO_SIZE = 240
export const STAGE_WELCOME = 0
export const STAGE_LOBBY = 1
export const STAGE_GAME = 2
export const STAGE_END = 3
export const BLOCK_MIN_DISTANCE = 64
export const PATICLE_NUMBER = 100
export const PARICLE_LIFESPAN = 120
export const HERO_COLOR = 0x2bae85
export const ENEMY_COLOR = 0xbbccdd